// Automatically generated by your Node Editor!
/*
void main() {
    vec3 localPosition = position;

    // Math calculated from node connections:
    float xOffset = localPosition.x + 4.5;
    float wave = sin(xOffset) * 1.4;
    localPosition.z += wave;

    gl_Position = projectionMatrix * modelViewMatrix * vec4(localPosition, 1.0);
}
*/
